# Generated by Django 6.0.4 on 2026-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(max_length=300),
        ),
    ]
